---
chapter:
  word: ምዕራፍ
  order: standard     # Use 'reverse' to change 'Chapter 1' to '1 Chapter'
section: ክፍል
table: ሰንጠረዥ
figure: ምስል
fig: ምስል
aside: ሳጥን
listing: ዝርዝር
equation: Equation
eq: Eq
frontmatter: ማውጫ
contents: ይዘቶች
